---
# Build test-redhat_test-config project object
- name: project.yml - Create project
  ansible.controller.project:
    name: "{{ project_name }}"
    description: "{{ common_description }}"
    organization: "{{ organization_name }}"
    scm_type: git
    scm_url: "{{ project_git_repo }}"
    scm_branch: "{{ project_git_branch }}"
    scm_credential: "{{ git_credential[0] }}"
    scm_update_on_launch: true     # Perform an update to the local repository before launching a job with this project.
    scm_update_cache_timeout: 60
    state: present
    #controller_config_file: "~/tower_cli.cfg"

# - name: project.ym - Wait for project synch
#   ansible.builtin.pause:
#     minutes: 1
